### ISSUE TITLE
Optionality - T*

### ISSUE THREAD

**Issue by pr0g** [hsutter/708#10]
One question I have that I couldn't find a satisfactory answer to in the paper (though it is referenced at the very top of page 3, second bullet, see below)

    "an X that only for { flexibility, optionality } happens to be passed by pointer (which in turn may or may not be safe to store to outlive the function call)"

is how to replace `T*` where `T*` is optional.

E.g.

```c++
void process(int a, Logger* logger)
{
    if (logger != nullptr) {
        logger->log(a);
    }
    ...
}
```

This is a pretty contrived example but could you do this using the new `in/out/inout` approach?

In the talk from CppCon 2020 it mentions `in` would be pass by `T*` when the size of the type is larger than some threshold, but then say if it's an object would one need to dereference it or use `->`? I'm just wondering with `in` would you also need `in*` or something similar? Or would the expectation be to use `std::optional` instead for these types of thing?

Overall I love the idea, I'd adopt this in a second if I could. I just wanted to make sure I understand this part, I've most likely missed something 🙈

Thanks!

Tom

**Comment by hsutter** [comment]
Thanks. Yes, I'd take either `in T*` or an `in optional<T>`, either is fine; two other alternatives are overloading and default arguments. Pointers are still a fine thing to pass when you want to do that to say `what` is being passed, in this case an optional parameter. The main place this proposal would remove raw `T*` parameters is when they are being used to express "how" not "what", such as for `out T` parameters.

I'll add a note about this in the doc. Thanks again.

**Comment by pr0g** [comment]
Awesome that makes perfect sense 😊 Thank you very much for following up and for all the fantastic work you do.

Best of luck with the paper and I look forward to one day getting to use this simpler, more beautiful C++ 🙂
