### ISSUE TITLE
Polymorphic Parameters

### ISSUE THREAD

**Issue by ngc92** [hsutter/708#15]
The paper considers passing const references as an optimization to prevent copying for large types, but a second motivation is to pass in types with polymorphic behaviour. This is effectively achieved by requiring trivial copyability, but it might be worth pointing that out more explicitly in the paper. At least to me (who is not a language expert), it wasn't really clear after a first reading of the paper whether the problem of passing derived classes through base class references was considered.

I think the underlying question still merits a bit more of a discussion, though. Because currently, there are still two different parameter passing variations in one syntax:
```
f(in A value);
```
could mean "Pass me an A that I can read from." or "Pass me anything that is an A or derived from A that I can read from". Being explicit about this might enable to detect and turn into compile errors some slicing bugs. Some examples 
```
struct A {
    virtual ~A() = default;
};

struct B : A {
};

void f(in A a) {
    A copy = a;     // potential slicing
}

void g(forward A a) {
    f(a);
}

void h(move A a) {
    f(a);
}

int main () {
    f(B());
    h(B());         // slicing
    g(B());         // error: expected deduced type 'A' but got 'B'
}
```

One situation where I think the concrete semantics make a potentially large difference is in the case of named constructors as discussed in the paper. What would (and should) happen in the following situation?
```
struct A {
  virtual void init() = 0;
  void named_ctor() out {
     init();
  }
}

struct B : A {
  void init() override {}
}

B x = B::named_ctor();
```

**Comment by hsutter** [comment]
Good point, thank you. I'll update 1.1.1 to mention this in the platform ABI section, something like this:

> For example, for an `in X` or `move X` parameter: If `X` is cheaply trivially copyable (and therefore nonpolymorphic; e.g., `int`) it is passed by value, the platform ABI defines what is the limit of “cheap” (e.g., size is 64 bits or smaller, possibly other characteristics).

And I'll add a Note along the following lines in 1.1.2:

> Polymorphic types are naturally passed by reference in all cases. For example, `in base` is perfectly sensible and equivalent to `base const&`. In some cases this proposal adds new expressive power; for example, `forward base` (or any specific non-template-parameter type) is hard to express today, but here it works fine to express a desire to forward an object whose type any of a subset of related types, and forwards the argument object’s const-ness (which is useful) and value category (which is likely not useful for a noncopyable type, but doesn’t hurt).

I think the `named_ctor` example is interesting, but is `B::named_ctor()` significantly different from `B::B()` (which doesn't exist in this `B`, but conceptually). That is, C++ doesn't support virtual constructors because you really need to know the type you're instantiating, and whether that's spelled `B::B` or `B::named_ctor` I think that still applies. Does that make sense?
