### ISSUE TITLE
Regarding 1.3.6 (Optional) Call site explicit side effects

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#17]
A few comments on the pros/cons of requiring the caller to annotate inout/out arguments (I am in favor though I am not totally sold on the need for inout/out parameters)

Pros
- to me this is a big plus in terms of readability which doesn't seem to be covered by the other points. I specifically mean that it's easy to see the flow of data without having to look at the function definition.
- I have seen code style guides that suggest parameters should always be passed by pointer rather than value because in the function call ```myfunc(&x)``` it is clear that x may be modified whereas in ```myfunc(x)```. I don't personally follow this convention because on balance I value the "this isn't null" assertion of a reference and, to a lesser extent, not having to use ->. However it is a compelling argument so a c++ user has to pick between two options with pros/cons. Without call site explicit side effects this would now be a trade off between passing by pointer or passing by inout/out and that's not a tradeoff you want to encourage.
- It would be easy to remove the requirement for call site explicit side effects (making them optional like ```override```) if they turned out to be a bad idea. It would be very difficult to make them compulsory in future if they were initially not compulsory.

Cons
- Regarding verbosity I think it's worth noting that inout/out parameters are an uncommon (to a debatable degree) use case so this change would only make the uncommon case more verbose which I think is arguably a good thing. If something is unusual I want it to be louder.

The third alternative to allow and check call site explicit side effects but not require them (like ```override```) is not addressed in 1.3.6 and might be worth considering. I suspect though that if you were to make it optional it wouldn't be worth expanding the scope to include.

**Comment by hsutter** [comment]
Thanks, added to the paper. It'll be there in the next update. If you let me know your name (here or by email) I'd be happy to add you to the Acknowledgments list -- ditto for all others who have offered feedback here but for whom I only see usernames.

**Comment by shaneasd** [comment]
My name is Shane Tapp
thanks
