### ISSUE TITLE
Testing/building software with the compiler outside of compiler explorer?

### ISSUE THREAD

**Issue by roxk** [hsutter/708#2]
Thanks for the proposal! I am all for the 3 improvements and I think the proposal just needs more experiments to prove itself.

I'm very interested in building real applications with the features so that they could be useful case studies. I see that there is already an experimental compiler in compiler explorer, any chance the compiler can be made publicly available so we can try it out?

In particular, it'd be great if it can be used with visual C++. I know visual studio 2019 already supports clang as explained in this [blog post](https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/), and that the experimental compiler is based on clang, so having it work with visual C++ would make experimenting with it and potentially building useful, real-world application so much easier.

I already anticipate IDE bugs or issues when testing out the compiler (e.g. broken intellisense due to unfamiliar keyword, i.e. in/out etc) but I'm willing to work-around/fix them as long as I could use the compiler outside of compiler explorer.

**Comment by Zastai** [comment]
The compiler used by cppx.godbolt.org as referenced in the talk is almost certainly https://github.com/lock3/cppx - so you should be able to build a clang binary from that already.

The extent to which this slots happily into Visual C++, I don't know - but it should be relatively easy to configure a CMake project to use that compiler specifically.

**Comment by hsutter** [comment]
Thank you for your interest, and sorry for the lag.

Yes, the experimental compiler is the one at https://gitlab.com/lock3/clang-cppx. Right now the only way to try it is via Godbolt. It's open source so you can clone the repo and build it locally yourself, but it's unsupported so you need to know how to build Clang yourself.

Currently the compiler supports `in`, `inout`, and `move`, but not `out` or `forward`. If you want to try out those three for now, please do and let us know what you find.
