### ISSUE TITLE
Why is mutation of out parameters restricted?

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#21]
My reading of section 1.1.2 (1.3.3 doesn't support this but also doesn't explicitly contradict it) is that this code is valid
```
void foo(out MyType x) {
x = MyType();
x = MyType(4); //You would (presumably) never want to do this
}
```
but this code is not
```
void foo(out MyType x) {
x = MyType();
x.data = 4; //but you might want to do this
}
```

Why is this? Why prevent modification of the out object once we know it has been assigned. It's already required that x is assigned on every path so presumably the compiler would be able to identify for a given line whether x was already assigned by that line or not.

The second example might arise if a constructor doesn't exist that puts the object into the exact state you want to return (keeping in mind the author of foo may not have or want control over the constructor of MyType).

It would seem that the solution is to write something like
```
void foo(out MyType x) {
auto x2 = MyType();
x2.data = 4;
x = std::move(x2);
}
```
I'm concerned that this doesn't express intent, doubles the amount of code the reader has to parse and the writer has to write and introduces an extra construction (which may or may not be able to be optimized away). I also worry that in the absence of the mentioned change (at the end of the notes in 1.3.1) to treat last use as move automatically the move would easily be overlooked. Moreover it just seems like an unnecessary restriction on what the user can do. Intuitively I think of an out parameter as like a local variable which is ```=uninitialized```.

**Comment by shaneasd** [comment]
I note that the comment ```// any const or non-const use of s is fine after this point``` seems to contradict my understanding so likely the issue here is just a lack of clarity.

**Comment by hsutter** [comment]
Both examples are legal. The second is like the `f1` example example in 1.3.3, after removing the first line that's labeled as an error.

**Comment by shaneasd** [comment]
That's pretty much the conclusion I reached but I think it is misresented by the explanation
> x is treated as a const lvalue, except that assignment-expression to x is also allowed

**Comment by hsutter** [comment]
Ah, I see -- fixed, pushed update.

The idea was to allow `out` to initialize an `=uninitialized` object even when the object is `const`, but that doesn't really work so I've eliminated that. It now says just "x is treated as a non-const lvalue` and the arguments column just says `any non-const lvalue`. Thanks!

**Comment by shaneasd** [comment]
Thanks for addressing.

That's actually a really interesting (albeit unrelated) limitation. Does that mean ```const X x = uninitialized``` is meaningless because it can never become initialized? That would be a shame since const is good http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-const (I realise the irony of link you your own guidelines) and I think of =uninitialized as deferred initialization rather than assignment so the usual reader assumptions about a const object not changing don't apply.

Since  this is a non-obvious and, in my opinion at least, undesirable limitation it would be nice to see the use case covered in the paper.
```
const X x = uninitialized;
generateX(out x);
```
