### ISSUE TITLE
1.3.6 suggest inout at callsite for inout parameters

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#22]
My objection is to this line: ```f2(out myb);``` given the declaration ```void f2(inout   B b);```.

Here it is communicated to the reader at the call site that the argument will be modified. It is ambiguous at the callsite whether the value passed in is relevant. Furthermore inout doesn't guarantee that all paths will mutate the argument (whereas out does).

if a reader sees ```f2(out myb);``` I think it would be surprising if they could not assume that
- the value of myb before the call will not affect the behavior of the function
- the value of myb after the function call is the value explicitly selected by the function

yet given the declaration of f2 above neither of these things can be assumed. I see no reason not to maintain symmetry between the modifiers on the declaration and the modifiers at the call site (aside from defaulting to in at the callsite)

**Comment by hsutter** [comment]
Right, that's a typo and should read `f2(inout myb)`. I've fixed it and it'll be in the next update to the paper, probably later this month. Thanks!
