### ISSUE TITLE
Assumption in 1.6 predicated on rejection of 1.3.6

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#23]
the notes in 1.6 assert
> Overloading ```in``` and ```out``` is naturally ambiguous because those two do not accept a subset or disjoint set of arguments, and so overloading cannot be allowed.

As far as I can see ```f(out x)``` and ```f(x)``` are always unambiguous. It's not clear to me whether you would consider the ```out``` to be part of the "argument" or not but either way I don't think there's an ambiguity. The point stands, however, if the suggestion in 1.3.6 to require the ```out``` is rejected. In the mean time I think the assertion here is at best conditional though I don't disagree with the actual conclusion.

**Comment by hsutter** [comment]
I'll add a note to 1.6 that they're naturally ambiguous in the absence of 1.3.6. It'll be in the next revision I push. Thanks!
