### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#24]
from section 2.1
> If two local variables x and y are explicitly uninitialized, then on every path x’s definite first use must precede y’s definite first use.

What does this mean? y isn't mentioned at all prior to this or after this and I assume both x and y are placeholders. As such when it says x must precede y it's not clear to me which is which. e.g. in the subsequent example with uninitialized variables ```j``` and ```s``` how can I tell which one is the x that must be initialized first.

My best guess is that is intended to be interpreted as "If two local variables x and y are explicitly uninitialized and one one code path x's definite first use precedes y's definite first use then x's definite first use must precede y's definite first use on all code paths". However I can't see a justification provided for that assertion and can't intuit a good reason for it myself.

**Comment by hsutter** [comment]
Good point, thanks. The point is that you have to initialize variables in declaration order.

I'll update the three bullets as follows:

   - A declaration of a local variable `x` that is initialized with `= uninitialized;` allocates stack memory as usual but does not invoke a constructor.
   - Every path containing `x`’s declaration must contain a definite first use of `x` __before the declaration or initialization of another local variable__, and that definite first use must be either to pass x to another function’s `out` parameter, or else be an assignment-expression to `x` (which can be from a single-object ex-pression or a possibly-empty `initializer_list`) that performs a single constructor call (usually direct-initialization) of `x` with the right-hand side expression treated as the argument to `x`’s constructor.
   - If two local variables `x` and `y` are declared __in that order__ and are explicitly uninitialized, then on every path `x`’s definite first use must precede `y`’s definite first use.

And I'll add this Note:

> The requirement to initialize in declaration order preserves that variable lifetimes continue to nest correctly, so that a later-declared local variable `y` can safely refer to a previously-declared variable `x` that will outlive `y` by construction.

I'll be in the next version of the PDF I push. Thanks!

**Comment by shaneasd** [comment]
thanks that clarifies a lot. I'm a bit concerned about that limitation but that's a separate issue so I'll raise it separately once the paper is updated.
