### ISSUE TITLE
1.3.2 example code unnecessarily ambiguous

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#26]
specifically I am referring to

```
void f1(inout X x)
{
    use(x);// ok
    x = 42;// ok and required
}
```

I think superficially inout could be thought of as in+out. With this in mind it might be reasonable for a reader to assume that therefore an inout parameter must be assigned to. I don't think the wording in the paper says this and I'm not asserting that it's ambiguous in what it says but I had to search a bit to find out the answer. With this in mind, it would be nice for this example code (being the only example of correct usage) to clarify by performing an operation other than assignment of x (e.g. ```x.y =  42```)

**Comment by hsutter** [comment]
Good point, I'll update the example to make the modification something other than assignment, perhaps `++x`, and update the comment.

I'll also update the description of `inout` to add "will":

   - An `inout` parameter is a parameter that the function body can read from and __will__ write to.

Thanks!

**Comment by shaneasd** [comment]
I was under the impression an inout parameter **may** be written to for any given path but **will** be written to on at least one path.

**Comment by hsutter** [comment]
That's correct. I was trying not to duplicate the information in the 1.1.2 table in each section (for DRY and to avoid having to keep them in sync if they evolve), but I'll look at making this clearer.

**Comment by shaneasd** [comment]
Maybe that's the way to go then. I remember the talk being very clear.
