### ISSUE TITLE
Is it possible to use the same idea in range loops? Local variables?

### ISSUE THREAD

**Issue by ivannp** [hsutter/708#29]
Just watched the cppcon 2020 talk - excited to see this effort!

Covering the parameter passing is essential. I started wondering, can this idea be extended to other similar constructs, like range loops, like local variables. It seems to make sense to use _intent_ approach for these too.

**Comment by hsutter** [comment]
@ivannp: Thanks, and yes. See [section 1.4 in the paper](https://github.com/hsutter/708/blob/main/708.pdf) which covers for loops. The paper contains other additional material that didn't fit into the time-limited talk.
