### ISSUE TITLE
Regarding example in 2.7: Dillema on definite last usage

### ISSUE THREAD

**Issue by Mick235711** [hsutter/708#30]
I am looking at example in `2.7 Together: Unified {copy,move} x {construction,assignment}`:
``` cpp
class X {
    widget w;
    gadget g;
public:
    X& operator=(in X that) out { // constructs *this if uninitialized, else assigns
        w = that.w; // moves from that if rvalue, else copies
        g = that.g;
        return *this;
    }
};
```
As per the current definition for `in` parameter `x`, it seems that only each definite last use of x that would be legal for an rvalue treats `x` as a non-`const` rvalue. However, in the `that` case, if the input `that` is indeed a non-`const` rvalue, the definite last usage is `g = that.g`, thus this line will be a move construction/assignment to `g`. However, the above line `w = that.w` will not be the definite last usage, so `that.w` will be a `const` lvalue, so this line must perform a copy construction/assignment when we should have done a move on both if we write this: (assume we allow overload)
``` cpp
class X {
    widget w;
    gadget g;
public:
    X& operator=(in X that) out { // same, but will only accept lvalue
        w = that.w; // both line copy
        g = that.g;
        return *this;
    }
    X& operator=(move X that) out {
        w = std::move(that.w); // note that move arguments have this problem too
        g = that.g; // last usage, treated as rvalue
        return *this;
    }
};
```
BTW, this feature seems very very useful, and I hope it could enter standard soon!

**Comment by hsutter** [comment]
This is a great point, thank you. I'll add something like the following to 1.2:

> When a local variable `x` has accessible data members `x.y` and `x.z`, then a definite first (or, last) use of `x.y` means a use that is not preceded (or, followed) by any other use of `x.y` or of `x` as a whole (but not affected by users of `x.z`).
