### ISSUE TITLE
Consideration of pros and cons of middle ground options regarding call site annotations

### ISSUE THREAD

**Issue by stan423321** [hsutter/708#31]
Section 1.3.6 of current proposal document describes mandatory use of confirmations of submitting objects to functions which will probably overwrite them using  `inout`, `out`, `forward` and `move` prefixes, and presents advantages and disadvantages of such approach which could be summarized as follows:
* advantage: user will not accidentally overwrite their variables;
* advantage: reader will not miss the variables being overwritten;
* advantage: other languages and some C/C++ conventions do this and it seems to work;
* disadvantage: some people will complain about verbosity.

To me, this sounds like a good summary of annotating variable usage in general as opposed to this particular setup, because they would seem to apply to any set of prefixes. And on a subjective level, `inout` looks really bad to me:

```
swap(inout a, inout b);
(inout std::cin) >> (inout c) >> (inout d); //parentheses for operators, or no?
(inout b) += c; //operator overloading is not limited to iostream, if ints and floats get special treatment
(inout std_map).clear(); //is that how it's supposed to work with implied this?
(inout std_map)[a] = b; //or is it (out(inout std_map)[a])? does it depend on the type of value?
(inout (inout std_map)[a]) += d; //see above
```

Maybe `this` is supposed to be exempt from annotations, I couldn't figure it out.

For no particular reason, let's consider a setup where we replace `inout` call prefix with unary `>`. Here's my completely biased pitch:
* users and readers related advantages are basically unchanged;
* the comparison to other languages applies on semantics level, but if we consider brevity of notation a competition, such C++ (`>`) is now arguably tying with pointers convention (`&`) and winning with Rust (`mut&`) and C# (`ref `) instead of (`inout ` / `mutable `) losing, arguably tying and arguably losing, respectively;
* some people will still complain, but since the notation is shorter, maybe a few less;
* there are some possible arguments against `inout` being special enough to deserve this notation and related teaching; while I could see shorter prefixes, or the same one if possible, used for other cases as well, `inout` is my breaking point, I guess, and relatively often removing it would just break the compilation;
* if there are going to be more types of parameters -- there probably are, especially if code styles start deprecating current undescribed parameters and return types -- there may be further discussion if they should get short call prefix forms, which does not seem like a major problem to me;
* grammar will probably be harder to figure out.

Anyway, I don't know if my ramblings are welcome here, but since issues are open, I thought I may at least get others' thoughts on this.

**Comment by hsutter** [comment]
Thanks! Actually I should have written `out` rather than `inout` in the example code, as the suggestion in the text was already suggesting just `out` (or `mutable`) for arguments that could be modified -- there is a data flow "out" as well as in.

I'll look to add examples like the ones you gave above to show the potential for verbosity. With reasonable precedence, we could get it down to something like this

~~~
std::swap(out a, out b);
out std::cin >> out c >> out d;
out b += c;
out mymap .clear();
out mymap [a] = b;
(out (out mymap)[a]) += d;
~~~

but which still needs to be called out as verbose.
