### ISSUE TITLE
Memory allocation with out

### ISSUE THREAD

**Issue by alexpanter** [hsutter/708#35]
Hi Mr. Herb Sutter,

First of all, I want to say what a wonderful idea! I just love the direction that the committee is taking these past few years. Where many people concern over the growing number of features, I just see an attempt to simplify and purify the language. So your work is greatly appreciated!

This is my question:
```cpp
bool CreateObject(out MyObject o);

// [...]
MyObject o = uninitialized;
if (!CreateObject(o)) {
    std::cerr << "Failed to create\n";
}
```

How will this proposal handle the memory for the output object? Clearly, I should not allocate (dynamic memory allocation scheme presumed) prior to calling the function. But if the function succeeds will it then also allocate memory? And how do I know where that memory is allocated? Sometimes, standard `new` will not be sufficient because I tend to use my own allocators. Can we perhaps use `out` in combination with another keyword to separate allocation from construction (like introducing a `construct_if` or similar). And what should I do when I later try to free this object?

A small improvement:
```cpp
// [...]
MyObject* o; // = uninitialized ??
if (!CreateObject(o))
```

So perhaps I misunderstand and this proposal is only meant to replace the use of `&` but not the pointer symbol `*`, because I certainly don't want to always only rely on wrapping my objects inside smart pointers.

**Comment by hsutter** [comment]
Hi Alexander,

The intent of the proposal is that

    MyObject o = uninitialized;

is still an object on the stack, but that the `= uninitialized` means we only allocate the memory for the object (as if `std::aligned_storage<sizeof(MyObject), alignof(MyObject)> __o; MyObject& o{__o};`).

Then the separate call

    CreateObject(o);

constructs it which means running a normal `MyObject constructor` (as if `new (&__o) MyObject(...);`). If the call returns normally, an uninitialized `out` argument is guaranteed to have been constructed (will need to be destroyed). (If the call throws an exception, any uninitialized `out` argument that was initialized will be destroyed again, so we still have accurate cleanup.)

I've tweaked the wording in the next draft of the paper to make this intent clearer, such as mentioning as-if `std::aligned_storage` and that there's no need of a program-visible 'did I construct the argument' flag.

Thanks!

**Comment by alexpanter** [comment]
Thank you!

I'm looking forward to being able to use this in my programs.
Would you happen to know if this proposal targets C++23 or C++26 (?).

Best,
Alexander

**Comment by hsutter** [comment]
No, it has not yet been even initially proposed to the committee because of the pandemic -- I am holding back updates (or in this case initial submissions) to nearly all my major proposals until after we can start meeting face-to-face again, which will not be until at least mid-2022. Please consider this a long-term and experimental (therefore by default should be assumed to fail) proposal.

**Comment by alexpanter** [comment]
Hi again,

I hope it's okay I write to you here, since we were already talking.. :)

I have been working on a proposal myself, and I was wondering whether you think there could be any interest, and how I should possibly proceed. Have never done this before, and I'm kind of a beginner in C++:

https://github.com/alexpanter/cpp-enum-proposal

Any feedback you could provide would be greatly appreciated.
Thanks!
